export interface IPlayerSeason {
  id?: number;
  seasonId?: number;
  divisionName: string;
  season: string;
  playerId?: number;
  teamName: string;
  name: string;
  surname: string;
  position: string;
  birthdate: Date | null;
  height: string;
  photoUrl: string;
  jerseyNr: string;
  pts: number;
  fga: number;
  fgm: number;
  fg3a: number;
  fg3m: number;
  fg2a: number;
  fg2m: number;
  fta: number;
  ftm: number;
  trb: number;
  orb: number;
  drb: number;
  ast: number;
  stl: number;
  blk: number;
  tov: number;
  fouls: number;
  offFouls: number;
  divisionId: number;
  teamId?: number;
}
