export const jerseyColorOptions = [
  { key: 1, text: "Orange", value: 1 },
  { key: 2, text: "Black", value: 2 },
  { key: 3, text: "Red", value: 3 },
  { key: 4, text: "Blue", value: 4 },
  { key: 5, text: "Purple", value: 5 },
  { key: 6, text: "Pink", value: 6 },
  { key: 7, text: "Yellow", value: 7 },
  { key: 8, text: "Olive", value: 8 },
  { key: 9, text: "Green", value: 9 },
  { key: 10, text: "Teal", value: 10 },
  { key: 11, text: "Brown", value: 11 },
  { key: 12, text: "Grey", value: 12 },
  { key: 13, text: "Violet", value: 13 },
];
